### ISSUE TITLE
LEMP Web Stack - phpinfo.php, apc.php, opcache.php missing

### ISSUE THREAD

**Issue by BornHanYolo** [MichaIng/DietPi-Docs#942] opened 2023-10-21 18:41 UTC
Files are missing when installing (79 LEMP: Nginx + MariaDB + PHP). 

May wish to update documentation: https://dietpi.com/docs/software/webserver_stack/ (LEMP Web Stack and most likely all Web Stacks) because of patch 8_14 https://github.com/MichaIng/DietPi/blob/fb0db339f63275d8924b80db7bca2d8d0410e6a0/.update/patches#L912 (Thank you, [pulpe](https://dietpi.com/forum/u/pulpe))

**Comment by Joulinar** [comment] 2023-10-21 18:48
Related to https://dietpi.com/forum/t/dietpi-v8-22-lemp-web-stack-phpinfo-php-apc-php-opcache-php-missing/18178

**Comment by MichaIng** [comment] 2023-10-21 19:31
Duplicate of #839 😉.

**Closed by MichaIng** 2023-10-21 19:31 UTC
Labels: enhancement
