### ISSUE TITLE
Porting docs from forum to DietPi-Docs - Procedure

### ISSUE THREAD

**Issue by StephanStS** [MichaIng/DietPi-Docs#139] opened 2020-10-24 12:57 UTC
I propose that we announce docu porting at this place in advance to the beginning of the work. I.e. here someone gets an overview who is working on which parts.

After the pull request is finished (reviewed, merged), the issue will be closed by the issue author to signal that his work is finished for now.

This behaves like a semaphore handling. :-)

@MichaIng, @fpetru: What do you think?

**Comment by MichaIng** [comment] 2020-10-24 13:13
It could be also 1 issue for 1 port, then assigned to whom is working on it and we could create a project "Porting software docs". Issues can be linked to pull requests as well, so when the pull request is merged, the issue is automatically as well, which automatically switches the task on the project to "Done".

I mean there are several ways to do which will work fine, on a (yet) small team like ours there are no strong reasons to prefer one over the other, or make it over-complicated, but alone to test and play a bid with the features that GitHub offers for project/task management 😉.

**Comment by StephanStS** [comment] 2020-10-24 13:23
Or we could handle it via the projects kanban board.  
<https://github.com/MichaIng/DietPi/projects>

**Comment by MichaIng** [comment] 2020-10-24 13:32
Jep, I created an automated kanban with reviews included. Probably without reviews would have been enough but I like to see how well (or not well) this works 😄.

**Comment by fpetru** [comment] 2020-10-24 18:52
@MichaIng @StephanStS I like the Kanban board, with 1 issue for 1 port of the documentation. 
Added 1 issue with web development section (carrying the web stacks, databases, and SSL).

**Closed** 2020-11-01 02:32 UTC
Labels: question
